on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up rust nightly
      run: |
        rustup update
        cargo update
        rustup override set nightly

    - name: Compile
      run: cargo build --verbose
