name: Check

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    name: Check Rust code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Rust nightly
      run: |
        rustup update
        rustup override set nightly
        rustup component add rustfmt

    - name: Check compilation
      run: cargo check --verbose

    - name: Check formatting
      run: cargo fmt --check
